# Generated by Django 3.1.7 on 2021-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='user_type',
            field=models.BooleanField(default=True),
        ),
    ]
