# Generated by Django 3.1.7 on 2021-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_details_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='user_type',
            field=models.BooleanField(default=False),
        ),
    ]
